In [68]:
from azure.storage.blob import BlobServiceClient
from azure.storage.blob import ContainerClient

from azure.core.credentials import AzureKeyCredential

from azure.ai.formrecognizer import FormRecognizerClient
from video_indexer import VideoIndexer

from azure.cognitiveservices.vision.face import FaceClient
from azure.cognitiveservices.vision.face.models import TrainingStatusType

from msrest.authentication import CognitiveServicesCredentials
from msrest.authentication import ApiKeyCredentials

from azure.cognitiveservices.vision.customvision.training import CustomVisionTrainingClient
from azure.cognitiveservices.vision.customvision.prediction import CustomVisionPredictionClient
from azure.cognitiveservices.vision.customvision.training.models import ImageFileCreateBatch, ImageFileCreateEntry, Region

In [69]:
from datetime import datetime
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
%matplotlib inline

from urllib.parse import urlparse
from io import BytesIO
from PIL import Image, ImageDraw
import os
import io
import time
import shutil
import pandas as pd

In [70]:
connection_string = "YOUR_CONNECTION_STRING_TO_AZURE_STORAGE"
service = BlobServiceClient.from_connection_string(conn_str=connection_string)

In [71]:
PREDICTION_ENDPOINT = 'YOUR_PREDICTION_ENDPOINT'
prediction_key = "YOUR_PREDICTION_KEY"
prediction_resource_id = "YOUR_PREDICTION_RESOURCE_ID"

In [72]:
TRAINING_ENDPOINT = "YOUR_TRAINING_ENDPOINT"
training_key = "YOUR_TRAINING_KEY"
training_resource_id = 'YOUR_TRAININ_RESOURCE_ID'

In [73]:
prediction_credentials = ApiKeyCredentials(in_headers={"Prediction-key": prediction_key})
predictor = CustomVisionPredictionClient(PREDICTION_ENDPOINT, prediction_credentials)
predictor.api_version

'3.1'

In [74]:
training_credentials = ApiKeyCredentials(in_headers={"Training-key": training_key})
trainer = CustomVisionTrainingClient(TRAINING_ENDPOINT, training_credentials)
trainer.api_version

'3.4-preview'

### Extract from ID Card and Boarding pass

In [75]:
AZURE_FORM_RECOGNIZER_ENDPOINT = "YOUR_ENDPOINT"
AZURE_FORM_RECOGNIZER_KEY = "YOUR_SECRET_KEY"

In [76]:
CONFIG = {
    'SUBSCRIPTION_KEY': 'YOUR_SUBSCRIPTION_KEY',
    'LOCATION': 'trial',
    'ACCOUNT_ID': 'YOUR_ACCOUNT_ID'
}
video_analysis = VideoIndexer(
    vi_subscription_key=CONFIG['SUBSCRIPTION_KEY'],
    vi_location=CONFIG['LOCATION'],
    vi_account_id=CONFIG['ACCOUNT_ID']
)

In [77]:
video_analysis.check_access_token()

Getting video indexer access token...
Access Token: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SWQiOiI4NGQyZGU2MS1mYTllLTRjMGEtYWE2Ny1mMzlkZjY0MmJlZjMiLCJQZXJtaXNzaW9uIjoiQ29udHJpYnV0b3IiLCJFeHRlcm5hbFVzZXJJZCI6Ijk2NjEwRjNCNTY3QTRBRkRCRDFDMDQxNzJFMTVDNkFFIiwiVXNlclR5cGUiOiJNaWNyb3NvZnRDb3JwQWFkIiwiSXNzdWVyTG9jYXRpb24iOiJUcmlhbCIsIm5iZiI6MTY2NzY0MDA1NCwiZXhwIjoxNjY3NjQzOTU0LCJpc3MiOiJodHRwczovL2FwaS52aWRlb2luZGV4ZXIuYWkvIiwiYXVkIjoiaHR0cHM6Ly9hcGkudmlkZW9pbmRleGVyLmFpLyJ9.a0Zz-KzvXNiOCEWMRpKgUfyM9JvTZoIChk3mIRDVPT8

In [78]:
endpoint = AZURE_FORM_RECOGNIZER_ENDPOINT
key = AZURE_FORM_RECOGNIZER_KEY

In [79]:
FACE_API_KEY = "15c1923c980b4909bbd516912d605c2a"
FACE_API_ENDPOINT = "https://udacity-face-student.cognitiveservices.azure.com/"

In [80]:
# Create a client
face_client = FaceClient(FACE_API_ENDPOINT, CognitiveServicesCredentials(FACE_API_KEY))

In [81]:
form_recognizer_client = FormRecognizerClient(endpoint=endpoint, credential=AzureKeyCredential(key))

In [82]:
def extract_id_card_data(file_name):
    with open(file_name, "rb") as f:
        poller = form_recognizer_client.begin_recognize_identity_documents(identity_document=f)
    id_documents = poller.result()
    info_dict = {}
    for idx, id_document in enumerate(id_documents):
        first_name = id_document.fields.get("FirstName")
        if first_name:
            info_dict['First Name'] = first_name.value[:]
        last_name = id_document.fields.get("LastName")
        if last_name:
            info_dict['Last Name'] = last_name.value[:]
        dob = id_document.fields.get("DateOfBirth")
        if dob:
            info_dict['Date of Birth'] = dob.value
    return info_dict

In [83]:
def extract_id_boarding_pass(model_id, file_name):
    with open(file_name, "rb") as f:
        poller = form_recognizer_client.begin_recognize_custom_forms(
           model_id=model_id, form=f, include_field_elements=True
       )
    forms = poller.result()
    
    info_dict = {}
    for idx, form in enumerate(forms): 
        for name, field in form.fields.items():
            if field.label_data:
                info_dict[field.label_data.text] = field.value
    print(info_dict)
    return info_dict

In [84]:
def extract_faces_from_video(save_path, video_id):
    if not os.path.exists(save_path):
        os.mkdir(save_path)
    info = video_analysis.get_video_info(video_id, video_language='English')
    images = []
    #img_raw = []
    img_strs = []
    for each_thumb in info['videos'][0]['insights']['faces'][0]['thumbnails']:
        if 'fileName' in each_thumb and 'id' in each_thumb:
            file_name = each_thumb['fileName']
            thumb_id = each_thumb['id']
            img_code = video_analysis.get_thumbnail_from_video_indexer(video_id,  thumb_id)
            img_strs.append(img_code)
            img_stream = io.BytesIO(img_code)
            #img_raw.append(img_stream)
            img = Image.open(img_stream)
            images.append(img)
    
    # Save the faces
    i = 1
    for img in images:
        img.save(f'{save_path}/human-face' + str(i) + '.jpg')
        i= i+ 1
    list_images = os.listdir(save_path)
    return list_images

In [85]:
def detect_face_from_image(selected_image):
    with open(selected_image, mode="rb") as image_data:
        detected_faces = face_client.face.detect_with_stream(
            image_data, 
            detection_model='detection_03', 
            recognition_model='recognition_04', 
            return_face_attributes=['qualityForRecognition']
        )
    if not detected_faces:
        raise Exception('No face detected from image {}'.format(single_image_name))        
    return detected_faces

In [86]:
def face_verification(card_id, faces_folder):
    # card_id = "ca-dl-avkash.png"
    list_images = extract_faces_from_video(faces_folder, video_id)
    with open(card_id, mode="rb") as image_data:
        faces = face_client.face.detect_with_stream(
            image_data, 
            detection_model='detection_03', 
            recognition_model='recognition_04', 
            return_face_attributes=['qualityForRecognition']
        )
    for face in faces:
        source_image_face_id = face.face_id
    
    group_faces_object = detect_face_from_image(os.path.join(faces_folder, list_images[0]))
    group_image_face_IDs_list = list(map(lambda x: x.face_id, group_faces_object))
    verify_result = face_client.face.verify_face_to_face(source_image_face_id, group_image_face_IDs_list[0])
    return verify_result

In [87]:
def lighter_detection(image_file_name):
    all_project = trainer.get_projects()
    isLighter_detected = False
    with open(image_file_name, "rb") as image_contents:
        results = predictor.detect_image(all_project[0].id, "lighter-object-detection-custom", image_contents.read())
        # Display the results.
        for prediction in results.predictions:
            if prediction.probability * 100 > 65:
                isLighter_detected = True
    return isLighter_detected

In [101]:
def information_validation(form_model_id, card_id, faces_folder, boarding_pass_file, video_id, manifest_data):
    manifest_data_columns = manifest_data.keys()
    card_info = extract_id_card_data(card_id)
    boarding_pass_info = extract_id_boarding_pass(form_model_id, boarding_pass_file)
    face_verify_result = face_verification(card_id, faces_folder)
    manifest_data_validation = pd.DataFrame(columns=manifest_data_columns)
    
    validation_result = {}
    
    if not lighter_detection(os.path.join(luggage_image_path, file_name)):
        LuggageValidation = True
    else:
        LuggageValidation = False
    
    print("Face confidence ", face_verify_result.confidence)
    if face_verify_result.is_identical and face_verify_result.confidence >= 0.65:
        PersonValidation = True
        message = "Dear Sir/Madam, Some of the information on your ID card does not match the flight manifest data, so you cannot board the plane.Please see a customer service representative."
        validation_result["PersonValidation"] = [message, True]
    else:
        PersonValidation = False
        message = "Dear Sir/Madam, Some of the information on your ID card does not match the flight manifest data, so you cannot board the plane.Please see a customer service representative."
        validation_result["PersonValidation"] = [message, False]
    
    
    
    for idx, row in manifest_data.iterrows():
        
        if card_info['First Name'].lower() != row['First Name'].lower() or card_info['Last Name'].lower() != row['Last Name'].lower():
            NameValidation = False
            message = "Dear Sir/Madam, Some of the information on your ID card does not match the flight manifest data, so you cannot board the plane.Please see a customer service representative."
            validation_result["NameValidation"] = [message, False]
        else:
            NameValidation = True
            message = "Dear Mr. Avkash Chauhan, You are welcome to flight # A123 leaving at 4:30 PM from San Francisco to Chicago. Your seat number is A5, and it is confirmed. We did not find a prohibited item (lighter) in your carry-on baggage,  thanks for following the procedure. Your identity is verified so please board the plane."
            validation_result["NameValidation"] =  [message, True]
        
        if datetime.strptime(row['Date of Birth'], '%m/%d/%Y') != datetime.strptime(str(card_info['Date of Birth']), '%Y-%m-%d'):
            DoBValidation = False
            message = "Dear Sir/Madam, Some of the information on your ID card does not match the flight manifest data, so you cannot board the plane.Please see a customer service representative."
            validation_result["DoBValidation"] = [message, False]
        else:
            message = "Dear Mr. Avkash Chauhan, You are welcome to flight # A123 leaving at 4:30 PM from San Francisco to Chicago. Your seat number is A5, and it is confirmed. We did not find a prohibited item (lighter) in your carry-on baggage,  thanks for following the procedure. Your identity is verified so please board the plane."
            DoBValidation = True
            validation_result["DoBValidation"] = [message, True]
            
        if boarding_pass_info['PST'] + " PST" != row['Boarding Time'] or boarding_pass_info['Date'] != row['Date'] or boarding_pass_info['To:'] != row['To'] or boarding_pass_info['From:'] != row['From'] or str(boarding_pass_info['Flight No.']) != str(row['Flight No.']) or boarding_pass_info['Seat'] != row['Seat'] or boarding_pass_info['Class'] != row['Class'][0:1]:
            BoardingPassValidation = False
            message = "Dear Sir/Madam, Some of the information in your boarding pass does not match the flight manifest data, so you cannot board the plane. Please see a customer service representative."
            validation_result["BoardingPassValidation"] = [message, False]
        else:
            BoardingPassValidation = True
            message = "Dear Mr. Avkash Chauhan, You are welcome to flight # A123 leaving at 4:30 PM from San Francisco to Chicago. Your seat number is A5, and it is confirmed. We did not find a prohibited item (lighter) in your carry-on baggage,  thanks for following the procedure. Your identity is verified so please board the plane."     
            validation_result["BoardingPassValidation"] = [message, True]

        manifest_data.at[idx,'NameValidation']=NameValidation
        manifest_data.at[idx,'DoBValidation']=DoBValidation
        manifest_data.at[idx,'PersonValidation']=PersonValidation
        manifest_data.at[idx,'BoardingPassValidation']=BoardingPassValidation
        manifest_data.at[idx,'LuggageValidation']=LuggageValidation
    message_result = ""
    for idx, item in validation_result.items():
        if item[1] == False:
            message_result = item[0]
        else:
            message_result = item[0]
    return manifest_data_validation, message_result, manifest_data

In [102]:
container = ContainerClient.from_connection_string(conn_str=connection_string, container_name="container-2")
blob_list = container.list_blobs()
for blob in blob_list:
    print(blob.name + '\n')

FlightManifest.csv

In [103]:
manifest_file = "manifest_table.csv"
with open(manifest_file, mode="wb") as f:
    f.write(container.download_blob(blob.name).readall())

In [104]:
manifest_data = pd.read_csv(manifest_file)
manifest_data.head(7)

,Carrier,Flight No.,Class,From,To,Date,Baggage,Seat,Gate,Boarding Time,Ticket No.,First Name,Last Name,Date of Birth,Sex,NameValidation,DoBValidation,PersonValidation,BoardingPassValidation,LuggageValidation
0,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",YES,25B,G1,10:00 AM PST,34236750,James,Jackson,10/12/1956,M,False,False,False,False,False
1,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",No,1A,G1,10:00 AM PST,34236748,James,Webb,12/15/1970,M,False,False,False,False,False
2,UA,234,Business,San Francisco,Chicago,"April 20, 2022",No,3D,G1,10:00 AM PST,34236749,Libby,Herold,2/10/1996,F,False,False,False,False,False
3,UA,234,Business,San Francisco,Chicago,"April 20, 2022",YES,34B,G1,10:00 AM PST,34236747,Radha,S. Kumar,3/5/1994,F,False,False,False,False,False
4,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",YES,34A,G1,10:00 AM PST,34236746,Sameer,Kumar,1/25/1990,M,False,False,False,False,False
5,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",No,20A,G1,10:00 AM PST,34236751,Akash chauhan,Chauhan,1/1/1990,M,False,False,False,False,False
6,UA,234,Business,San Francisco,Chicago,"April 20, 2022",No,96G,G1,10:00 AM PST,300A6746F,Alexandre Joseph,Sample,8/31/1977,M,False,False,False,False,False

In [105]:
id_card_folder = "id-cards"
boarding_pass_folder = "boarding-pass"
video_id = 'b6ce115f2e'
form_model_id = "016a99c8-601c-4d29-9151-7b1782d08725"

In [106]:
boarding_pass_name = "Alexandre-Joseph.pdf"
card_id_name = "Alexandre-Joseph.png"
faces_folder = "Alexandre-Joseph-faces"

In [107]:
file_name = 'lighter-3.jpg'
luggage_image_path = "lighter-images"

In [108]:
boarding_pass_file = os.path.join(boarding_pass_folder, boarding_pass_name)
card_id = os.path.join(id_card_folder,card_id_name)

In [109]:
person_data = manifest_data.take([6])

In [110]:
%%time
manifest_data_validation, message, updated_manifest_data = information_validation(form_model_id, card_id, faces_folder, boarding_pass_file, video_id, person_data)

{'Passenger Name': 'Alexandre Joseph Sample', 'Carrier': 'UA', 'Flight No.': '234', 'Class': 'B', 'From:': 'San Francisco', 'Date': 'April 20, 2022', 'Baggage': 'YES', 'Seat': '96G', 'To:': 'Chicago', 'GATE': 'G1', 'PST': '10:00 AM'}
Getting video info for: b6ce115f2e
Getting thumbnail from video: b6ce115f2e, thumbnail: cc5725d7-d4c0-4df6-a0f0-03097cd06cff
Getting thumbnail from video: b6ce115f2e, thumbnail: 10960d19-8220-47ef-afb1-1b2b98ee7177
Getting thumbnail from video: b6ce115f2e, thumbnail: f78a27ec-828d-47b8-b8e6-9d8c2c9ddcb5
Getting thumbnail from video: b6ce115f2e, thumbnail: b20d9105-8e9f-4655-bb85-40b87e0447ca
Face confidence  0.93688
CPU times: total: 328 ms
Wall time: 34.9 s

In [111]:
updated_manifest_data

,Carrier,Flight No.,Class,From,To,Date,Baggage,Seat,Gate,Boarding Time,Ticket No.,First Name,Last Name,Date of Birth,Sex,NameValidation,DoBValidation,PersonValidation,BoardingPassValidation,LuggageValidation
6,UA,234,Business,San Francisco,Chicago,"April 20, 2022",No,96G,G1,10:00 AM PST,300A6746F,Alexandre Joseph,Sample,8/31/1977,M,True,True,True,True,True

In [112]:
message

'Dear Mr. Avkash Chauhan, You are welcome to flight # A123 leaving at 4:30 PM from San Francisco to Chicago. Your seat number is A5, and it is confirmed. We did not find a prohibited item (lighter) in your carry-on baggage,  thanks for following the procedure. Your identity is verified so please board the plane.'

In [113]:
new_manifest_data = manifest_data.copy()
new_manifest_data.loc[6] = updated_manifest_data.values[0]

In [114]:
new_manifest_data

,Carrier,Flight No.,Class,From,To,Date,Baggage,Seat,Gate,Boarding Time,Ticket No.,First Name,Last Name,Date of Birth,Sex,NameValidation,DoBValidation,PersonValidation,BoardingPassValidation,LuggageValidation
0,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",YES,25B,G1,10:00 AM PST,34236750,James,Jackson,10/12/1956,M,False,False,False,False,False
1,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",No,1A,G1,10:00 AM PST,34236748,James,Webb,12/15/1970,M,False,False,False,False,False
2,UA,234,Business,San Francisco,Chicago,"April 20, 2022",No,3D,G1,10:00 AM PST,34236749,Libby,Herold,2/10/1996,F,False,False,False,False,False
3,UA,234,Business,San Francisco,Chicago,"April 20, 2022",YES,34B,G1,10:00 AM PST,34236747,Radha,S. Kumar,3/5/1994,F,False,False,False,False,False
4,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",YES,34A,G1,10:00 AM PST,34236746,Sameer,Kumar,1/25/1990,M,False,False,False,False,False
5,UA,234,Economy,San Francisco,Chicago,"April 20, 2022",No,20A,G1,10:00 AM PST,34236751,Akash chauhan,Chauhan,1/1/1990,M,False,False,False,False,False
6,UA,234,Business,San Francisco,Chicago,"April 20, 2022",No,96G,G1,10:00 AM PST,300A6746F,Alexandre Joseph,Sample,8/31/1977,M,True,True,True,True,True